"set runtimepath+=~/.vim_runtime

" eliminate .viminfo file into .vim
set viminfo+=n~/.vim/viminfo

" change mru_vim file location
let MRU_File = $HOME . '/.vim/vim_mru_files'

"source ~/.vim_runtime/vimrcs/basic.vim
"source ~/.vim_runtime/vimrcs/filetypes.vim
"source ~/.vim_runtime/vimrcs/plugins_config.vim
"source ~/.vim_runtime/vimrcs/extended.vim

try
source ~/.vim_runtime/my_configs.vim
catch
endtry

