" ---------------My Setting----------------

" ---------------
" Tmp Files
" ---------------

set viminfo+=n~/.cache/vim/viminfo
let MRU_File = $HOME . '/.cache/vim/vim_mru_files'

" ---------------
" Source File Paths
" ---------------
source ~/.vim_runtime/vimrcs/basic.vim
source ~/.vim_runtime/vimrcs/plugins_config.vim
